id = "word-highlight-lsp"
name = "Word Highlight"
version = "0.1.5"
authors = ["Marco Ivaldi <raptor@0xdeadbeef.info>"]
description = "Highlight all occurrences of selected words with multiple colors to quickly identify them in code."
repository = "https://github.com/0xdea/zed-highlight"
schema_version = 1

[language_servers.zed-highlight-lsp]
name = "Zed Highlight LSP"
languages = [
    "Assembly",
    "Astro",
    "C",
    "C++",
    "CMake",
    "CSharp",
    "CSS",
    "CSV",
    "Dart",
    "devicetree",
    "Diff",
    "Docker Compose",
    "Dockerfile",
    "Elixir",
    "Elm",
    "Erlang",
    "Git Attributes",
    "Git Commit",
    "Git Config",
    "Git Ignore",
    "Git Rebase",
    "Go",
    "Go Mod",
    "Go Work",
    "Gradle",
    "GraphQL",
    "Groovy",
    "Haskell",
    "HCL",
    "HTML",
    "ini",
    "Java",
    "JavaScript",
    "JSON",
    "JSONC",
    "Kotlin",
    "LaTeX",
    "Linker Script",
    "LLVM IR",
    "LOG",
    "Lua",
    "Make",
    "Markdown",
    "Nix",
    "OCaml",
    "PHP",
    "Plain Text",
    "PowerShell",
    "Properties",
    "Proto",
    "Python",
    "Ruby",
    "Rust",
    "Scala",
    "SCSS",
    "Shell Script",
    "Smali",
    "Solidity",
    "SQL",
    "Strace",
    "Svelte",
    "Swift",
    "SystemVerilog",
    "Terraform",
    "TOML",
    "TSX",
    "TypeScript",
    "Typst",
    "VHDL",
    "Vue.js",
    "WebAssembly Text Format",
    "XML",
    "YAML",
    "Yara",
    "Zig",
]
