[package]
name = "zed-highlight-lsp"
version = "0.1.3"
authors = ["Marco Ivaldi <raptor@0xdeadbeef.info>"]
edition = "2024"
description = "An LSP implemented for Zed that allows to highlight all occurrences of selected words."
homepage = "https://0xdeadbeef.info/"
repository = "https://github.com/0xdea/zed-highlight"
license = "MIT"
keywords = ["zed", "zed-extension", "lsp-server", "vuln-dev", "code-review"]
categories = ["security", "development-tools", "text-editors"]

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "sync", "time", "io-std"] }
serde_json = "1.0"
regex = "1.12"

[dev-dependencies]
tower = "0.4" # tower-lsp depends on this version of tower

[[bin]]
name = "zed-highlight-lsp"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[profile.dev]
debug = false

[lints]
workspace = true
