name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-all:
    name: build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: zed-highlight-lsp-linux-x86_64.tar.gz
            arch: x86_64

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: zed-highlight-lsp-linux-aarch64.tar.gz
            arch: aarch64

          - target: x86_64-apple-darwin
            os: macOS-latest
            name: zed-highlight-lsp-darwin-x86_64.tar.gz
            arch: x86_64

          - target: aarch64-apple-darwin
            os: macOS-latest
            name: zed-highlight-lsp-darwin-aarch64.tar.gz
            arch: aarch64

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: zed-highlight-lsp-windows-x86_64.zip
            arch: x86_64

          # - target: aarch64-pc-windows-msvc
          #   os: windows-latest
          #   name: zed-highlight-lsp-windows-aarch64.zip
          #   arch: aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          target: ${{ matrix.target }}
      - name: build
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --manifest-path lsp/Cargo.toml --target ${{ matrix.target }}
      - name: package
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf "../../../${{ matrix.name }}" zed-highlight-lsp
      - name: package-windows
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf "../../../${{ matrix.name }}" zed-highlight-lsp.exe
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  release:
    name: release
    needs: build-all
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: publisn
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: "*.tar.gz"
          generate_release_notes: true
